// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzauGEVwakObpiq75rr28417rQ9eTOqNc',
    appId: '1:302572681611:web:963b44977b51e40a08978e',
    messagingSenderId: '302572681611',
    projectId: 'ex2-iris',
    authDomain: 'ex2-iris.firebaseapp.com',
    storageBucket: 'ex2-iris.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DQ2QtFt87ogXboFnppIAGRkTMFf0Hps',
    appId: '1:302572681611:android:3978ae0b00b06ec508978e',
    messagingSenderId: '302572681611',
    projectId: 'ex2-iris',
    storageBucket: 'ex2-iris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUa4BqdWxPH2CrY982fMTM3RodXG-DYfU',
    appId: '1:302572681611:ios:3c54cba3da1badc508978e',
    messagingSenderId: '302572681611',
    projectId: 'ex2-iris',
    storageBucket: 'ex2-iris.appspot.com',
    iosBundleId: 'com.example.ex2S10IrisSgastume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUa4BqdWxPH2CrY982fMTM3RodXG-DYfU',
    appId: '1:302572681611:ios:3c54cba3da1badc508978e',
    messagingSenderId: '302572681611',
    projectId: 'ex2-iris',
    storageBucket: 'ex2-iris.appspot.com',
    iosBundleId: 'com.example.ex2S10IrisSgastume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzauGEVwakObpiq75rr28417rQ9eTOqNc',
    appId: '1:302572681611:web:ee9ed8be7de471e708978e',
    messagingSenderId: '302572681611',
    projectId: 'ex2-iris',
    authDomain: 'ex2-iris.firebaseapp.com',
    storageBucket: 'ex2-iris.appspot.com',
  );
}
